language: elixir
elixir:
  - 1.9
otp_release:
  - 22.0
sudo: false

matrix:
  include:
    - env: PHOENIX_VERSION=1.2.0
    - env: PHOENIX_VERSION=1.3.0
    - env: PHOENIX_VERSION=1.4.0

before_script:
  - MIX_ENV=ci PHOENIX_VERSION=$PHOENIX_VERSION mix deps.get

script:
  - mix test.lint
  - mix test